"""
Lab 4 - Comprehensive smoke test that exercises the API end-to-end and writes
its output to ``api_test_results.txt``. Also serves as documentation of the
expected request/response shapes.

Run:
    python lab4_api/smoke_test.py
"""

from __future__ import annotations

import contextlib
import io
import json
import sys
from pathlib import Path
from uuid import uuid4

import httpx

BASE = "http://127.0.0.1:8765"
RESULT_FILE = Path(__file__).parent / "api_test_results.txt"


def banner(buf: io.StringIO, title: str) -> None:
    buf.write("\n" + "=" * 70 + "\n")
    buf.write(title + "\n")
    buf.write("=" * 70 + "\n")


def dump_json(buf: io.StringIO, label: str, data) -> None:
    buf.write(f"\n--- {label} ---\n")
    if isinstance(data, (dict, list)):
        buf.write(json.dumps(data, indent=2) + "\n")
    else:
        buf.write(str(data) + "\n")


def http(buf: io.StringIO, method: str, url: str, **kwargs):
    buf.write(f"\n>>> {method} {url}\n")
    if "json" in kwargs:
        buf.write(">>> body: " + json.dumps(kwargs["json"]) + "\n")
    try:
        r = httpx.request(method, url, timeout=30, **kwargs)
    except httpx.HTTPError as exc:
        buf.write(f"!!! HTTP error: {exc}\n")
        return None
    buf.write(f"<<< {r.status_code} {r.reason_phrase}\n")
    buf.write(f"<<< content-type: {r.headers.get('content-type')}\n")
    return r


def main() -> int:
    out = io.StringIO()

    out.write("RestorAI Lab 4 - API Test Results\n")
    out.write("Generated by lab4_api/smoke_test.py\n")
    out.write("Author: Abdullah Noor - 2022029\n")

    # --------------------------------------------------------------- 1: root
    banner(out, "TEST 1 - GET / (service banner)")
    r = http(out, "GET", f"{BASE}/")
    if r is not None:
        dump_json(out, "response body", r.json())

    # --------------------------------------------------------------- 2: health
    banner(out, "TEST 2 - GET /health (dependency check)")
    r = http(out, "GET", f"{BASE}/health")
    if r is not None:
        dump_json(out, "response body", r.json())

    # --------------------------------------------------------------- 3: openapi
    banner(out, "TEST 3 - GET /openapi.json (auto-generated schema)")
    r = http(out, "GET", f"{BASE}/openapi.json")
    if r is not None:
        schema = r.json()
        dump_json(out, "info", schema["info"])
        dump_json(out, "paths", sorted(schema["paths"].keys()))
        dump_json(out, "components.schemas", sorted(schema["components"]["schemas"].keys()))
        chat_schema = schema["components"]["schemas"]["ChatRequest"]
        dump_json(out, "ChatRequest schema", chat_schema)

    # --------------------------------------------------------------- 4: validation
    banner(out, "TEST 4 - POST /chat schema validation (rejects empty message)")
    r = http(out, "POST", f"{BASE}/chat", json={"message": "", "thread_id": "v1"})
    if r is not None:
        dump_json(out, "response body", r.json())

    banner(out, "TEST 5 - POST /chat schema validation (rejects bad thread_id)")
    r = http(out, "POST", f"{BASE}/chat",
             json={"message": "hi", "thread_id": "bad space id"})
    if r is not None:
        dump_json(out, "response body", r.json())

    # --------------------------------------------------------------- 6: chat
    banner(out, "TEST 6 - POST /chat (synchronous - full pipeline)")
    thread_id = str(uuid4())
    payload = {
        "message": "I have water rings on my oak coffee table. Help me restore it.",
        "thread_id": thread_id,
    }
    r = http(out, "POST", f"{BASE}/chat", json=payload)
    if r is not None:
        body = r.json()
        out.write("\n--- response body (preview) ---\n")
        out.write(json.dumps({
            "thread_id": body.get("thread_id"),
            "status": body.get("status"),
            "step_count": body.get("step_count"),
            "elapsed_ms": body.get("elapsed_ms"),
            "tool_calls": [t["name"] for t in body.get("tool_calls", [])],
            "answer_first_500": (body.get("answer") or "")[:500],
        }, indent=2))
        out.write("\n")

    # --------------------------------------------------------------- 7: persistence
    banner(out, "TEST 7 - POST /chat (same thread_id - persistence over HTTP)")
    payload2 = {
        "message": "Now give me JUST the shopping list as a bullet list.",
        "thread_id": thread_id,
    }
    r = http(out, "POST", f"{BASE}/chat", json=payload2)
    if r is not None:
        body = r.json()
        out.write("\n--- response body (preview) ---\n")
        out.write(json.dumps({
            "thread_id": body.get("thread_id"),
            "status": body.get("status"),
            "step_count": body.get("step_count"),
            "answer_first_300": (body.get("answer") or "")[:300],
        }, indent=2))
        out.write("\n")
        out.write("(Note: with a real OPENAI_API_KEY, the agent has access to the\n"
                  " checkpointed messages from TEST 6 because the same thread_id is\n"
                  " reused. The AsyncSqliteSaver is shared across requests via\n"
                  " FastAPI's lifespan context.)\n")

    # --------------------------------------------------------------- 8: stream
    banner(out, "TEST 8 - POST /stream (Server-Sent Events)")
    out.write(f"\n>>> POST {BASE}/stream\n")
    out.write(">>> body: " + json.dumps(payload2) + "\n")
    try:
        with httpx.stream("POST", f"{BASE}/stream", json=payload2, timeout=30) as resp:
            out.write(f"<<< {resp.status_code} {resp.reason_phrase}\n")
            out.write(f"<<< content-type: {resp.headers.get('content-type')}\n")
            out.write("\n--- SSE event stream ---\n")
            for line in resp.iter_lines():
                if line:
                    out.write(line + "\n")
                else:
                    out.write("\n")
    except httpx.HTTPError as exc:
        out.write(f"!!! HTTP error: {exc}\n")

    # --------------------------------------------------------------- footer
    banner(out, "SUMMARY")
    out.write(
        "\nThe API exposes:\n"
        "  GET  /            -> service banner\n"
        "  GET  /health      -> dependency check (checkpointer + KB)\n"
        "  POST /chat        -> synchronous chat (returns ChatResponse)\n"
        "  POST /stream      -> SSE stream of agent execution\n\n"
        "Lab 4 mandatory tasks demonstrated:\n"
        "  Task 1 (Schema validation)  -> tests 4 + 5 (422 on bad input)\n"
        "  Task 2 (Persistence over HTTP) -> tests 6 + 7 share thread_id\n"
        "                                    AsyncSqliteSaver opened ONCE in\n"
        "                                    FastAPI lifespan (see app/api/main.py)\n"
        "  Task 3 (Streaming via SSE)  -> test 8, content-type text/event-stream\n"
        "                                with event: meta / token / tool_call /\n"
        "                                tool_result / done frames.\n"
    )

    text = out.getvalue()
    print(text)
    RESULT_FILE.write_text(text, encoding="utf-8")
    print(f"\nResults also written to: {RESULT_FILE}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
